=cut homer_diff_cont 2 

## will fail when applying to group

inputFile=design_matrix

ncore=1
mem=16000

## merge peak for each comparison

module load bedtools


cd {{jid}}

cat ${COL1}.bed ${COL2}.bed > ${COL3}.homer_diff.merged.bed

sort -k1,1 -k2,2n ${COL3}.homer_diff.merged.bed > ${COL3}.homer_diff.merged.st.bed

bedtools merge -c 4 -o collapse -i ${COL3}.homer_diff.merged.st.bed > ${COL3}.homer_diff.merged.bed

module load homer/4.10

module load R/3.4.0

mkdir -p homer_diff_results

getDifferentialPeaks ${COL3}.homer_diff.merged.bed ${COL1}_tag/ ${COL2}_tag/ -F 0 -P 1 > homer_diff_results/${COL3}.gain.peak

getDifferentialPeaks ${COL3}.homer_diff.merged.bed ${COL2}_tag/ ${COL1}_tag/ -F 0 -P 1 > homer_diff_results/${COL3}.loss.peak

rm ${COL3}.homer_diff*


