#!shell

=cut CT 2 


ncore=1
mem=80000

src=/home/yli11/Tools/ATAC_STARR_seq_analysis

# call peak

module load macs2/2.1.1
module load bedtools

cd {{jid}}

# macs2 callpeak --nomodel --shift -100 --extsize 200 -p 0.01 -t */*dedup.bam -g {{macs_genome}} -n Merged
macs2 callpeak --nomodel --shift -100 --extsize 200 -p 0.01 -t */*rmdup.DNA.dedup.bam */*group.RNA.dedup.bam -g {{macs_genome}} -n Merged

bedtools intersect -a Merged_peaks.narrowPeak -b {{black_list}} -v -wa > Merged_peaks.rmblck.narrowPeak

module load conda3/202011

source activate /home/yli11/.conda/envs/captureC

module load texlive/20190410

mkdir Differential_analysis
module load subread/2.0.5  

/home/yli11/.conda/envs/captureC/bin/python $src/call_ATAC-STARR_regulatory-regions.py -i Merged_peaks.rmblck.narrowPeak -o Differential_analysis/ -q 0.1 -d */*rmdup.DNA.dedup.bam -r */*group.RNA.dedup.bam

cd Differential_analysis

# run jupyter notebook

yes | cp -rf /research/rgs01/home/clusterHome/yli11/.local/share/jupyter/kernels/ ~/.local/share/jupyter/


export XDG_RUNTIME_DIR=""
mkdir /scratch_space/{{username}}/$$
export JUPYTER_RUNTIME_DIR=/scratch_space/{{username}}/$$

cp $src/ChrAcc_and_Activity_Region-Calling_liyc.ipynb .
jupyter nbconvert --to notebook --execute ChrAcc_and_Activity_Region-Calling_liyc.ipynb  --output diff_analysis_plots --ExecutePreprocessor.timeout=-1 --allow-errors 

rm ChrAcc_and_Activity_Region-Calling_liyc.ipynb

jupyter nbconvert diff_analysis_plots.ipynb --to html

# create bw files, TODO




=cut email 4 all


cd {{jid}}

module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
cp /home/yli11/HemTools/share/NGS_pipeline/multiqc_config.yaml .

multiqc .

export PATH=$PATH:"/home/yli11/HemTools/bin"

module load python/2.7.13

cd Differential_analysis

bdg_to_bw.py --data_frame -f DESEQ2_results.csv --binSize 10


send_email_v1.py -a multiqc_report.html,Differential_analysis/diff_analysis_plots.html -m "{{jid}} is finished. The bw files are generating and will notify you when they are done." -j {{jid}} --common












