=cut BWA 1

module load bwa/0.7.16a
module load samtools/1.7

inputFile=input

ncore=1
mem=4000

module load fastqc/0.11.5
fastqc ${COL1} -o {{jid}}
fastqc ${COL2} -o {{jid}}
bwa mem ref.fa ${COL1} ${COL2}  |samtools view -bS - > {{jid}}/${COL3}.bam
cd {{jid}}
samtools sort -o ${COL3}.st.bam ${COL3}.bam
samtools index ${COL3}.st.bam
samtools flagstat ${COL3}.st.bam > ${COL3}.flagstat
samtools stats ${COL3}.st.bam > ${COL3}.stats
samtools idxstats ${COL3}.st.bam > ${COL3}.idxstats



=cut qc 2 BWA

ncore=1
mem=40000
cd {{jid}}

module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

touch multiqc_config.yaml

echo 'read_count_multiplier: 0.001' >> multiqc_config.yaml
echo 'read_count_prefix: "K"' >> multiqc_config.yaml
echo 'read_count_desc: "thousands"' >> multiqc_config.yaml

multiqc .

