#!shell

=cut BWA 1

module load bwa/0.7.16a
module load samtools/1.7

inputFile=input

ncore=6
mem=10000
q=priority

module load fastqc/0.11.5

# fastqc ${COL1} -o {{jid}}

# fastqc ${COL2} -o {{jid}}

bwa mem -t 6 {{index_file}} ${COL1} ${COL2}  |samtools view -bS - > {{jid}}/${COL3}.bam
cd {{jid}}
samtools sort -@ 6 -o ${COL3}.st.bam ${COL3}.bam
samtools index ${COL3}.st.bam
# samtools markdup -@ $ncore {{jid}}/${COL3}.fixmate.st.bam {{jid}}/${COL3}.markdup.bam
# samtools markdup -@ 6 ${COL3}.st.bam ${COL3}.markdup.st.bam
# samtools index ${COL3}.markdup.st.bam
samtools flagstat ${COL3}.st.bam > ${COL3}.flagstat
samtools stats ${COL3}.st.bam > ${COL3}.stats
samtools idxstats ${COL3}.st.bam > ${COL3}.idxstats

module load picard/2.9.4 gatk/4.1.8.0 R/3.5.1

java -jar /hpcf/apps/picard/install/2.9.4/picard.jar MarkDuplicates I=${COL3}.st.bam O=${COL3}.markdup.st.bam CREATE_INDEX=true VALIDATION_STRINGENCY=SILENT M=${COL3}.picard.metrics.txt

java -jar /hpcf/apps/picard/install/2.9.4/picard.jar MarkDuplicates I=${COL3}.st.bam O=${COL3}.rmdup.st.bam CREATE_INDEX=true REMOVE_DUPLICATES=true 


# java -jar /hpcf/apps/picard/install/2.9.4/picard.jar CollectInsertSizeMetrics I=${COL3}.st.bam O=${COL3}.insert_size_metrics.txt H=${COL3}.insert_size_histogram.pdf 
java -jar /hpcf/apps/picard/install/2.9.4/picard.jar CollectInsertSizeMetrics I=${COL3}.st.bam O=${COL3}.insert_size_metrics.txt H=${COL3}.insert_size_histogram.pdf INCLUDE_DUPLICATES=true 

# convert to bw

module load python/2.7.15-rhel7

bamCoverage -b ${COL3}.markdup.st.bam -o ${COL3}.markdup.CPM.bw -p 6 -bs 10000 --normalizeUsing CPM 
bamCoverage -b ${COL3}.rmdup.st.bam -o ${COL3}.rmdup.CPM.bw -p 6 -bs 10000 --normalizeUsing CPM 



=cut qc 2 BWA

ncore=1
mem=40000
cd {{jid}}

module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

touch multiqc_config.yaml

echo 'read_count_multiplier: 0.001' >> multiqc_config.yaml
echo 'read_count_prefix: "K"' >> multiqc_config.yaml
echo 'read_count_desc: "thousands"' >> multiqc_config.yaml

multiqc .

