#!shell

=cut BWA 1

module load bwa/0.7.16a
module load samtools/1.7

inputFile=input

ncore=15
mem=10000
q=priority

module load fastqc/0.11.5

fastqc ${COL1} -o {{jid}}


bwa mem -t 15 {{index_file}} ${COL1} |samtools view -bS - > {{jid}}/${COL2}.bam
cd {{jid}}
samtools sort -@ 15 -o ${COL2}.st.bam ${COL2}.bam
samtools index ${COL2}.st.bam
# samtools markdup -@ $ncore {{jid}}/${COL2}.fixmate.st.bam {{jid}}/${COL2}.markdup.bam
# samtools markdup -@ 6 ${COL2}.st.bam ${COL2}.markdup.st.bam
# samtools index ${COL2}.markdup.st.bam
samtools flagstat ${COL2}.st.bam > ${COL2}.flagstat
samtools stats ${COL2}.st.bam > ${COL2}.stats
samtools idxstats ${COL2}.st.bam > ${COL2}.idxstats

samtools view -b -F 4 ${COL2}.st.bam > ${COL2}.st.mapped.bam
samtools index ${COL2}.st.mapped.bam


module load picard/2.9.4 gatk/4.1.8.0 R/3.5.1

java -jar /hpcf/apps/picard/install/2.9.4/picard.jar MarkDuplicates I=${COL2}.st.bam O=${COL2}.markdup.st.bam CREATE_INDEX=true VALIDATION_STRINGENCY=SILENT M=${COL2}.picard.metrics.txt


=cut qc 2 BWA

ncore=1
mem=40000
cd {{jid}}

module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

touch multiqc_config.yaml

echo 'read_count_multiplier: 0.001' >> multiqc_config.yaml
echo 'read_count_prefix: "K"' >> multiqc_config.yaml
echo 'read_count_desc: "thousands"' >> multiqc_config.yaml

multiqc .

