#!shell

=cut cas 1

ncore=1
mem=20000
# q=gpu_rhel7

module load conda3
source activate /home/yli11/.conda/envs/Cas_Offinder/

#module load cas-offinder

cd {{jid}}

cas-offinder input.list C matches.bed

module load python/2.7.13

cas_offinder_output_to_bed.py matches.bed {{motif_length}} ABCsd934hdsfsd

# cas_offinder_output_to_bed.py matches.bed 8 ABCsd934hdsfsd

sort -k1,1 -k2,2n matches.bed.bed > matches.bed.sorted

module load bedtools

{{check}}

rm matches.bed.bed

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}


