#!shell

=cut count 1

inputFile=input

ncore=1
mem=20000
# q={{queue}}

# for debug purposes
module purge
echo $PATH


PATH=/home/yli11/HemTools/bin:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/etc:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/lpp/mmfs/bin:/usr/lpp/mmfs/lib:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/puppetlabs/bin



module load parallel
module load bwa/0.7.16a
module load samtools/1.7
module load trimmomatic/0.36
module load flash
module load fastqc/0.11.5


mkdir {{jid}}/${COL3}_results

fastqc ${COL1} -o {{jid}}/log_files/
fastqc ${COL2} -o {{jid}}/log_files/

trimmomatic PE ${COL1} ${COL2} -threads 4 -baseout {{jid}}/${COL3}_results/${COL3} ILLUMINACLIP:/hpcf/apps/trimmomatic/install/0.36/adapters/TruSeq3-PE.fa:2:30:10:2:True LEADING:3


# Run flash to combine reads 

cd {{jid}}/${COL3}_results

flash ${COL3}_1P ${COL3}_2P --max-overlap=120 --min-overlap={{FLASH_min_overlap}} --output-prefix=${COL3}


bwa mem -t 6 /home/yli11/Data/Human/hg38/bwa_16a_index/hg38.fa ${COL3}.extendedFrags.fastq > ${COL3}.sam
samtools sort -o ${COL3}.bam ${COL3}.sam
samtools index ${COL3}.bam
samtools flagstat ${COL3}.bam > ${COL3}.flagstat
samtools stats ${COL3}.bam > ${COL3}.stats


module load conda3/202011

source activate /home/yli11/.conda/envs/cutadaptenv/

cd ../..

																														

/home/yli11/.conda/envs/cutadaptenv/bin/python /research_jude/rgs01_jude/groups/tsaigrp/projects/Genomics/common/src/cas9engineering/count_indels_integrations2.py --bed {{gRNA_bed}} --ref /home/yli11/Data/Human/hg38/fasta/hg38.fa --bam {{jid}}/${COL3}_results/${COL3}.bam --out {{jid}}/${COL3}_results/${COL3}.counts.tsv --setting cas9  {{addon_parameters}}

=cut email 3 all

# q={{queue}}

cd {{jid}}



module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
cp /home/yli11/HemTools/share/NGS_pipeline/multiqc_config.yaml .

multiqc .

export PATH=$PATH:"/home/yli11/HemTools/bin"

module load python/2.7.13


mv multiqc_report.html count_indel_report.html

send_email_v1.py -a count_indel_report.html -m "{{jid}} is finished" -j {{jid}} --common



