#!shell

=cut count 1

inputFile=input

ncore=2
mem=20000
q={{queue}}


module load parallel
module load bwa
module load samtools/1.7
module load trimmomatic
module load flash
module load fastqc/0.11.5


mkdir {{jid}}/${COL3}_results

fastqc ${COL1} -o {{jid}}/log_files/
fastqc ${COL2} -o {{jid}}/log_files/

trimmomatic PE ${COL1} ${COL2} -threads 4 -baseout {{jid}}/${COL3}_results/${COL3} ILLUMINACLIP:/hpcf/apps/trimmomatic/install/0.36/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3


# Run flash to combine reads 

cd {{jid}}/${COL3}_results

flash ${COL3}_1P ${COL3}_2P --max-overlap=120 --output-prefix=${COL3}


bwa mem -t 6 /rgs01/project_space/tsaigrp/Genomics/common/genomes/hg38/hg38.fa ${COL3}.extendedFrags.fastq > ${COL3}.sam
samtools sort -o ${COL3}.bam ${COL3}.sam
samtools index ${COL3}.bam
samtools flagstat ${COL3}.bam > ${COL3}.flagstat
samtools stats ${COL3}.bam > ${COL3}.stats


module load conda3

source activate /home/yli11/.conda/envs/crispresso2_env/

cd ../..

#bed_fix.py ${COL4} output.bed

/home/yli11/.conda/envs/crispresso2_env/bin/python /rgs01/project_space/tsaigrp/Genomics/common/src/cas9engineering/count_indels_integrations2.py --bed ${COL4} --ref /rgs01/project_space/tsaigrp/Genomics/common/genomes/hg38/hg38.fa --bam {{jid}}/${COL3}_results/${COL3}.bam --out {{jid}}/${COL3}_results/${COL3}.counts.tsv --setting {{setting}} --site ${COL5}

=cut email 3 all



cd {{jid}}

module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

multiqc .

export PATH=$PATH:"/home/yli11/HemTools/bin"

module load python/2.7.13

mv multiqc_report.html count_indel_report.html

send_email_v1.py -a count_indel_report.html -m "{{jid}} is finished" -j {{jid}} --common



