#!shell


=cut BaseE 1

inputFile=input_list

ncore=1
mem=12000
q={{queue}}


PATH=/home/yli11/HemTools/bin:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/etc:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/lpp/mmfs/bin:/usr/lpp/mmfs/lib:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/puppetlabs/bin
export PATH=$PATH:"/home/yli11/HemTools/bin"

module load conda3/202011

source activate /home/yli11/.conda/envs/cutadaptenv/

module load samtools/1.7
module load bowtie2/2.2.9

# CRISPRessoPooled -r1 ${COL1} -r2 ${COL2} --name ${COL3} -o {{jid}}/${COL3}_results -f ${COL4} --ignore_substitutions --keep_intermediate --dump --limit_open_files_for_demux --min_reads_to_use_region 100
CRISPRessoPooled -r1 ${COL1} -r2 ${COL2} --name ${COL3} -o {{jid}}/${COL3}_results -f ${COL4} --ignore_substitutions --keep_intermediate --dump --limit_open_files_for_demux --min_reads_to_use_region 3


=cut email 2 all


ncore=1
mem=2000
q={{queue}}



cd {{jid}}

PATH=/home/yli11/HemTools/bin:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/etc:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/lpp/mmfs/bin:/usr/lpp/mmfs/lib:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/puppetlabs/bin
export PATH=$PATH:"/home/yli11/HemTools/bin"
module load python/2.7.13

send_email_v1.py -m "{{jid}} is finished!" -j {{jid}}



