#!shell


=cut BaseE 1

inputFile=input_list

## columns are gRNA, P1, P2, R1, R2, name

ncore=1
mem=12000

in_silico_PCR.pl -s {{genome_fasta}} -a ${COL2} -b ${COL3} > {{jid}}/${COL6}_results.txt 2> {{jid}}/${COL6}_amplicons.fasta

module load conda3

source activate /home/yli11/.conda/envs/crispresso2_env/

amplicon=`tail -n 1 {{jid}}/${COL6}_amplicons.fasta`

CRISPResso -r1 ${COL4} -r2 ${COL5} --amplicon_seq $amplicon --guide_seq ${COL1} --quantification_window_size 10 --quantification_window_center -10 --base_editor_output -o {{jid}}/${COL6}

=cut email 2 BaseE[*]

inputFile=input_list

ncore=1
mem=2000

module load python/2.7.13

cd {{jid}}

zip -r ${COL6}.zip ${COL6}

send_email_v1.py -a ${COL6}.zip -m "${COL5} crispresso2 base editor is finished" -j {{jid}} --common



