#!shell


=cut BaseE 1

inputFile=bam_list

ncore=10
mem=1000

q={{queue}}


PATH=/home/yli11/HemTools/bin:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/etc:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/lpp/mmfs/bin:/usr/lpp/mmfs/lib:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/puppetlabs/bin
export PATH=$PATH:"/home/yli11/HemTools/bin"

module load conda3/202402

source activate /home/yli11/.conda/envs/cutadaptenv/

module load samtools/1.7
module load bowtie2/2.2.9

CRISPRessoWGS --skip_failed -p $ncore -r {{genome_fasta}} --quantification_window_size {{w_size}} --quantification_window_center {{center}} --base_editor_output --conversion_nuc_from {{ref}} --conversion_nuc_to {{alt}} --min_reads_to_use_region {{min_reads}} -b $COL1 --name $COL2 -o {{jid}}/${COL2}_results -f {{region_file}} {{addon_parameters}}
# CRISPResso_on_CBLB_CBE_chr21_40289751_40289774
module load python/2.7.13

cd {{jid}}

crispressoWGS_get_eff.py ${COL2} info.tsv {{ref}} {{alt}} {{SNP}}

## need to check for sgRNA length
## 3/2/2021, no need
crispressoWGS_get_background.py ${COL2} info.tsv {{SNP}}



## need to check for sgRNA length
## 3/2/2021, fixed
crispressoWGS_allele_edit_eff.py ${COL2} info.tsv {{ref}} {{alt}} {{SNP}}

# too slow
# table2heatmap.py -f ${COL2}.max_edit.tsv -o ${COL2}.max_edit.pdf -d gRNA

## need to check for sgRNA length
## 3/2/2021, no need
# crispressoWGS_plot_all_conversion.py ${COL2} info.tsv {{SNP}}


=cut email 2 all


ncore=1
mem=2000
q=standard



cd {{jid}}

PATH=/home/yli11/HemTools/bin:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/etc:/hpcf/lsf/lsf_prod/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/lpp/mmfs/bin:/usr/lpp/mmfs/lib:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/puppetlabs/bin
export PATH=$PATH:"/home/yli11/HemTools/bin"
module load python/2.7.13

send_email_v1.py -m "{{jid}} is finished!" -j {{jid}}



