#!shell



=cut bam 1

inputFile=input_tsv

ncore=1
mem=16000

### create a sorted, indexed, filtered bam file in bam_file folder

module load conda3/5.1.0
source activate /home/yli11/.conda/envs/cutruntools/
module load R/4.1.0
module load trimmomatic/0.36
module load java/1.8.0_60
module load meme/4.11.2
module load bedtools/2.25.0
module load bowtie2/2.2.9
module load picard/2.9.4
module load bedops/2.4.35
module load hdf5/1.10.4
module load perl/5.20.1
module load samtools/1.3.1
module load gcc/4.8.5
module load java/1.8.0_66



# Please give absolute path to file
peak_file=${COL1} #a narrowPeak file
bam_file=${COL2}
base=${COL3}
jid={{jid}}

pythonbin=/home/yli11/.conda/envs/cutruntools/bin
memebin=/hpcf/apps/meme/install/4.11.2/bin
bedopsbin=/hpcf/authorized_apps/rhel7_apps/bedops/install/2.4.35/bin
bedtoolsbin=/hpcf/apps/bedtools/install/2.25.0/bin
genome_sequence={{genome_fasta}}
samtoolsbin=/hpcf/apps/samtools/install/1.3.1/bin
makecutmatrixbin={{Liu_Nan_pipeline_path_atactk}}
Rscriptbin=/hpcf/authorized_apps/rhel7_apps/R/install/3.5.1/bin
extrasettings={{Liu_Nan_pipeline_path_root}}

## not sure what this is for, but will keep it
pythonldlibrary=/home/yli11/.conda/envs/cutruntools/lib
ldlibrary=`echo $LD_LIBRARY_PATH | tr : "\n" | grep -v $pythonldlibrary | paste -s -d:`
unset LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$pythonldlibrary:$ldlibrary

cd $jid
mkdir -p $base
cd $base

dest=filtered.bam
mkdir bam_file
outbam=bam_file/$dest
#note that 1024 means read is PCR or optical duplicate
$samtoolsbin/samtools view -b -h -f 3 -F 4 -F 8 -F 1024 -o $outbam $bam_file #previous version
$samtoolsbin/samtools sort $outbam -o ${outbam}.sorted
mv ${outbam}.sorted $outbam
$samtoolsbin/samtools index $outbam
echo "finish samtools"


=cut bw 2 bam[*]


inputFile=input_tsv

ncore=1
mem=16000


module load conda3/5.1.0
source activate /home/yli11/.conda/envs/cutruntools/
module load R/4.1.0
module load trimmomatic/0.36
module load java/1.8.0_60
module load meme/4.11.2
module load bedtools/2.25.0
module load bowtie2/2.2.9
module load picard/2.9.4
module load bedops/2.4.35
module load hdf5/1.10.4
module load perl/5.20.1
module load samtools/1.3.1
module load gcc/4.8.5
module load java/1.8.0_66
module load homer


# Please give absolute path to file
peak_file=${COL1} #a narrowPeak file
bam_file=${COL2}
base=${COL3}
jid={{jid}}

pythonbin=/home/yli11/.conda/envs/cutruntools/bin
memebin=/hpcf/apps/meme/install/4.11.2/bin
bedopsbin=/hpcf/authorized_apps/rhel7_apps/bedops/install/2.4.35/bin
bedtoolsbin=/hpcf/apps/bedtools/install/2.25.0/bin
genome_sequence={{genome_fasta}}
samtoolsbin=/hpcf/apps/samtools/install/1.3.1/bin
makecutmatrixbin={{Liu_Nan_pipeline_path_atactk}}
Rscriptbin=/hpcf/authorized_apps/rhel7_apps/R/install/3.5.1/bin
extrasettings={{Liu_Nan_pipeline_path_root}}

## not sure what this is for, but will keep it
pythonldlibrary=/home/yli11/.conda/envs/cutruntools/lib
ldlibrary=`echo $LD_LIBRARY_PATH | tr : "\n" | grep -v $pythonldlibrary | paste -s -d:`
unset LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$pythonldlibrary:$ldlibrary

cd $jid
mkdir -p $base
cd $base
echo "generating bw file"
mkdir cut_sites
cd cut_sites
outbam=tcut_sites.bam
outbdg=tcut_sites.bdg
outbw=${COL3}.bw
chrom_size={{chrom_size}}
bam_file=../bam_file/filtered.bam
alignmentSieve --minMappingQuality {{minMappingQuality}} -b $bam_file -o  $outbam --filterMetrics metrics.txt --maxFragmentLength {{maxFragmentLength}} --shift 0 0
bedtools genomecov -ibam $outbam -g $chrom_size -bga -5 > $outbdg
module load ucsc/051223
sort -k1,1 -k2,2n $outbdg > $outbdg.sorted
bedGraphToBigWig $outbdg.sorted $chrom_size $outbw
# rm $outbam
# rm $outbdg

=cut email 3 all

module load python/2.7.13

cd {{jid}}

mv *.lsf log_files

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}













