#!shell



=cut FT 1

inputFile=input_tsv

ncore=1
mem=16000


module load conda3/202402
source activate /home/yli11/.conda/envs/cutruntools/
module load R/4.1.0
module load trimmomatic/0.36
module load java/1.8.0_60
module load meme/4.11.2
module load bedtools/2.25.0
module load bowtie2/2.2.9
module load picard/2.9.4
module load bedops/2.4.35
module load hdf5/1.10.4
module load perl/5.20.1
module load samtools/1.3.1
module load gcc/4.8.5
module load java/1.8.0_66



# Please give absolute path to file
peak_file=${COL1} #a narrowPeak file
bam_file=${COL2}
base=${COL3}
jid={{jid}}

pythonbin=/home/yli11/.conda/envs/cutruntools/bin
memebin=/hpcf/apps/meme/install/4.11.2/bin
bedopsbin=/hpcf/authorized_apps/rhel7_apps/bedops/install/2.4.35/bin
bedtoolsbin=/hpcf/apps/bedtools/install/2.25.0/bin
# genome_sequence=/home/yli11/Data/Human/hg19/fasta/hg19.fa
# samtoolsbin=/hpcf/apps/samtools/install/1.3.1/bin
# makecutmatrixbin=/home/yli11/Programs/cut_run_pipeline_Nan_Liu/git/atactk/scripts
# Rscriptbin=/hpcf/authorized_apps/rhel7_apps/R/install/3.5.1/bin
# extrasettings=/home/yli11/Programs/cut_run_pipeline_Nan_Liu
# motif_file=/home/yli11/Data/Motif_database/Human/human.meme

genome_sequence={{genome_fasta}}
samtoolsbin=/hpcf/apps/samtools/install/1.3.1/bin
makecutmatrixbin={{Liu_Nan_pipeline_path_atactk}}
Rscriptbin=/hpcf/authorized_apps/rhel7_apps/R/install/3.5.1/bin
extrasettings={{Liu_Nan_pipeline_path_root}}
motif_file={{motif_file}}

## not sure what this is for, but will keep it
pythonldlibrary=/home/yli11/.conda/envs/cutruntools/lib
ldlibrary=`echo $LD_LIBRARY_PATH | tr : "\n" | grep -v $pythonldlibrary | paste -s -d:`
unset LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$pythonldlibrary:$ldlibrary

p=0.00050

echo "remove blacklist"
# blacklist=$extrasettings/hg19.blacklist.bed
blacklist={{black_list}}
cat $peak_file | grep -v -e "chrM" | $bedopsbin/sort-bed - | $bedopsbin/bedops -n 1 - $blacklist > $jid/"$base".filtered.narrowPeak

# cp $peak_file $jid/"$base".filtered.narrowPeak


$bedtoolsbin/bedtools getfasta -fi $genome_sequence -bed $jid/"$base".filtered.narrowPeak -fo $jid/"$base".fa
$pythonbin/python $extrasettings/macs2.narrow.aug18/fix_sequence.py $jid/"$base".fa



cd $jid
mkdir $base
cd $base
fimo_dir=motif_mapping
mkdir $fimo_dir
cd $fimo_dir
for m in `cat {{motif_list}}`; do
mkdir $m
echo $m
$memebin/fimo --verbosity 1 --motif $m --thresh $p --parse-genomic-coord -oc $m $motif_file ../../"$base".fa
$bedopsbin/gff2bed < $m/fimo.gff | awk 'BEGIN {IFS="	"; OFS="	";} {print $1,$2,$3,$4,$5,$6}' > $m/fimo.bed
done


cd ..
dest=filtered.bam
mkdir centipede
outbam=centipede/$dest
#note that 1024 means read is PCR or optical duplicate
$samtoolsbin/samtools view -b -h -f 3 -F 4 -F 8 -F 1024 -o $outbam $bam_file #previous version
$samtoolsbin/samtools sort $outbam -o ${outbam}.sorted
mv ${outbam}.sorted $outbam
$samtoolsbin/samtools index $outbam
echo "finish samtools"

echo "plot footprint figures"
echo `pwd`
for i in `ls -1 $fimo_dir`; do #shows a list of motifs
echo "Doing $i..."
fimo_d=$fimo_dir/$i
tmp=`echo $i|cut -d "." -f3|wc -c`
mlen=$(( tmp - 1 ))
$pythonbin/python $makecutmatrixbin/make_cut_matrix -v -b '(25-150 1)' -d -o 0 -r 100 -p 1 -f 3 -F 4 -F 8 -q {{minMappingQuality}} $outbam $fimo_d/fimo.bed > $fimo_d/fimo.cuts.freq.txt
$Rscriptbin/Rscript $extrasettings/macs2.narrow.aug18/run_centipede_parker.R $fimo_d/fimo.cuts.freq.txt $fimo_d/fimo.bed $fimo_d/fimo.png $mlen
done

echo "generating bw file"
mkdir cut_sites
cd cut_sites
outbam=tcut_sites.bam
outbed=tcut_sites.bed
outbdg=tcut_sites.bdg
outbw=${COL3}.bw
chrom_size={{chrom_size}}
bam_file=../centipede/$dest
alignmentSieve --minMappingQuality {{minMappingQuality}} -b $bam_file -o  $outbam --filterMetrics metrics.txt --maxFragmentLength {{maxFragmentLength}} --shift 0 0
bedtools genomecov -ibam $outbam -g $chrom_size -bga -5 > $outbdg
/home/yli11/Programs/kentUtils/bin/linux.x86_64/bedGraphToBigWig $outbdg $chrom_size $outbw
rm $outbam
# rm $outbed
rm $outbdg

=cut email 3 FT

module load python/2.7.13

cd {{jid}}

rm *.fa

rm *.filtered.narrowPeak

mv *.lsf log_files

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}













