#!shell
=cut CLIP 1

ncore=8
mem=15000

inputFile=input

bash /home/yli11/Tools/ENCODE_eclip_seq/run_SE_siqi_data.sh ${COL1} ${COL2} {{jid}}/${COL2}_results
# bash /home/yli11/Tools/ENCODE_eclip_seq/run_SE_siqi_data_hg38.sh ${COL1} ${COL2} {{jid}}/${COL2}_results

=cut email 3 all

cd {{jid}}

module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
cp /home/yli11/HemTools/share/NGS_pipeline/multiqc_config.yaml .

multiqc .

export PATH=$PATH:"/home/yli11/HemTools/bin"

module load python/2.7.13

mv multiqc_report.html eclip_QC.html

send_email_v1.py -a eclip_QC.html -m "{{jid}} is finished" -j {{jid}} --common




