#!shell

=cut qc 1

inputFile=input

ncore=1
mem=10000

module load fastqc/0.11.5

fastqc -q ${COL1} 
# fastqc ${COL2} 

# module load flash

# flash ${COL1} ${COL2} --max-overlap=120 --output-prefix=${COL3}


=cut email 2 all


module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

cp /home/yli11/HemTools/share/NGS_pipeline/multiqc_config.yaml .


multiqc .

export PATH=$PATH:"/home/yli11/HemTools/bin"

module load python/2.7.13

mv multiqc_report.html fastqc_report.html

send_email_v1.py -a fastqc_report.html -m "{{jid}} is finished" -j {{jid}} --common

