#!shell


=cut GATK 1

inputFile=input_list

ncore=1
mem=16000


module load picard/2.9.4 gatk/3.5 
module load samtools/1.9

genome_fasta={{genome_fasta}}
bam=${COL1}
output=${COL2}
mkdir {{jid}}/$output

cp $genome_fasta {{jid}}/$output/



ref={{jid}}/$output/$(basename $genome_fasta)


two_step_GATK={{no_known_SNPs}}

known_SNP={{known_SNP}}



    
java -jar /hpcf/apps/picard/install/2.9.4/picard.jar CreateSequenceDictionary R= $ref  O= ${ref%.*}.dict

samtools faidx $ref	
	

java -jar /hpcf/apps/picard/install/2.9.4/picard.jar AddOrReplaceReadGroups I= $bam O= $output.bam RGID=test RGLB=test RGPL=illumina RGPU=Hart_Center RGSM=test

java -jar /hpcf/apps/picard/install/2.9.4/picard.jar ReorderSam I= $output.bam O= $output.sorted.bam R= $ref CREATE_INDEX=TRUE


if [ "$two_step_GATK" = true ] ; then

	echo -e "["$(date)"]\tStart two step GATK.."

    java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T HaplotypeCaller -R $ref -I $output.sorted.bam -o $output.known.vcf 
	
	known_SNP=$output.known.vcf
	
	echo -e "["$(date)"]\tFiltering Variants.."
	java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T VariantFiltration -R $ref -V $known_SNP -filterName FS -filter "FS > 30.0" -filterName QD -filter "QD < 2.0" -o $output.filtered.known.vcf	
	
	known_SNP=$output.filtered.known.vcf
	
fi



#Perform BQSR
echo -e "["$(date)"]\tPerforming BQSR.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T BaseRecalibrator -I $output.sorted.bam -R $ref -knownSites $known_SNP -o $output.Base.Recal.table

#Print recalibrated reads
echo -e "["$(date)"]\tPrinting recalibrated reads.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T PrintReads -R $ref -I $output.sorted.bam -BQSR $output.Base.Recal.table -o $output.BQSR.bam 


#Run HaplotypeCaller
echo -e "["$(date)"]\tRunning HaplotypeCaller.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T HaplotypeCaller -R $ref -I $output.BQSR.bam  -o $output.BQSR.vcf 

mv $output*.vcf {{jid}}/$output/
mv $output*.bam {{jid}}/$output/
mv $output*.table {{jid}}/$output/

=cut email 4 all

module load python/2.7.13

cd {{jid}}

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}




