#!shell


=cut align 1

inputFile=input

ncore=20
mem=4000

module load fastqc/0.11.5
# cd /research_jude/rgs01_jude/groups/tsaigrp/projects/Genomics/common/projects/targeted_sequencing/06282022_gRNAseq_VK/analysis

module load seqtk

module load flash

flash -f 100 ${COL1} ${COL2} -o {{jid}}/${COL3}.merged 2>&1 | tee ${COL3}_flash.log

mv ${COL3}_flash.log {{jid}}/log_files

cd {{jid}}

# VK2108.merged.fastq.gz.extendedFrags.fastq

fastqc ${COL3}.merged.extendedFrags.fastq

# cutadapt
module load conda3/202011

source activate /home/yli11/.conda/envs/cutadaptenv

/home/yli11/.conda/envs/cutadaptenv/bin/cutadapt -j 8 -m {{min_length}} -e 0.15 -O 6 -a ${COL6} -o ${COL3}.merged.trimed.fastq ${COL3}.merged.extendedFrags.fastq



src=/home/yli11/Tools/gRNA_sequencing

source activate /home/yli11/.conda/envs/captureC


echo `which python`

# COL5 is scaffold sequence, Varun used internal primer so the sacffold sequence can be truncated, users need to input the sequence
module load gcc/13.1.0
/home/yli11/.conda/envs/captureC/bin/python $src/align_reads4.py ${COL3}.merged.trimed.fastq ${COL4} ${COL5} 

mv ${COL3}*zip log_files

mv ${COL3}*html log_files

module load bowtie2 seqtk

seqtk seq ${COL3}.merged.trimed.fastq -A > ${COL3}.FQ2FA.fa


bowtie2-build ${COL3}.FQ2FA.fa ${COL3}_index

# echo $'>expected_sequence\n${COL4}${COL5}' > ${COL3}.fa

echo $'>expected_sequence'>${COL3}.fa
echo $COL4$COL5 >>${COL3}.fa

bowtie2 --very-sensitive -p 10 -x ${COL3}_index -f -U ${COL3}.fa -S ${COL3}.sam -a

module load samtools/1.7

samtools view ${COL3}.sam | cut -f 1-6 > ${COL3}.sam.tsv

python $src/indel_frequency.py ${COL3}.sam.tsv


module load calitas/1.0
module load gcc/13.1.0
/home/yli11/.conda/envs/captureC/bin/python $src/find_contaminants.py ${COL3}.merged.trimed.alignment.csv  ${COL3}




=cut email 2 all

ncore=20
mem=2000
# cd /research_jude/rgs01_jude/groups/tsaigrp/projects/Genomics/common/projects/targeted_sequencing/06282022_gRNAseq_VK/analysis

cp {{gRNA_to_check}} {{jid}}/

cd {{jid}}



src=/home/yli11/Tools/gRNA_sequencing

module load conda3/202011
source activate /home/yli11/.conda/envs/captureC
module load gcc/13.1.0
/home/yli11/.conda/envs/captureC/bin/python $src/gRNA_summarize2.py



export XDG_RUNTIME_DIR=""
mkdir /scratch_space/{{username}}/$$
export JUPYTER_RUNTIME_DIR=/scratch_space/{{username}}/$$

cp $src/gRNA_contaminant_finding.ipynb gRNA_contaminant_finding_tmp.ipynb

cp $src/user_gRNA_percent.ipynb user_gRNA_percent_tmp.ipynb

jupyter nbconvert --to notebook --execute gRNA_contaminant_finding_tmp.ipynb  --output gRNA_contaminant_finding --ExecutePreprocessor.timeout=-1 --allow-errors 

rm gRNA_contaminant_finding_tmp.ipynb

jupyter nbconvert gRNA_contaminant_finding.ipynb --to html

jupyter nbconvert --to notebook --execute user_gRNA_percent_tmp.ipynb  --output user_gRNA_percent --ExecutePreprocessor.timeout=-1 --allow-errors 

rm user_gRNA_percent_tmp.ipynb

jupyter nbconvert user_gRNA_percent.ipynb --to html

# organize

mkdir -p fastq_vis

mv *trimfq.png  fastq_vis

rm *trimfq*

rm *1k*



module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

multiqc .

export PATH=$PATH:"/home/yli11/HemTools/bin"

module load python/2.7.13


send_email_v1.py -a multiqc_report.html -m "{{jid}} is finished" -j {{jid}} --common



