#!shell


=cut hichip 1

inputFile=hicpro_input

ncore=2
mem=80000

cd {{jid}}

cd ${COL1}

module load conda3
source activate /home/yli11/.conda/envs/trimgalore/
cd fastq

cd ${COL1}

bash run_trim_galore.sh

cd ../..

module load hic-pro/2.11.1

time HiC-Pro -c ../hicpro.config.txt -i fastq -o hicpro_results

cd hicpro_results

source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

multiqc .

cd hic_results/matrix/${COL1}

module load python/2.7.13

hicpro2fithic.py -i raw/20000/GSM3489137_20000.matrix -b raw/20000/GSM3489137_20000_abs.bed -s iced/20000/GSM3489137_20000_iced.matrix.biases

source activate /home/yli11/.conda/envs/fithic/

fithic -f fithic.fragmentMappability.gz -i fithic.interactionCounts.gz -o fithic_result -r 20000 -t fithic.biases.gz -p 2

cd ../../../

cd ..


module purge
module load conda3
source activate /home/yli11/.conda/envs/hichipper/
module load bedtools samtools/1.9
module load htslib
module load macs2
module load bedtools
which R
cp ../hichipper.yaml .
# hichipper, version 0.7.7

# hichipper --basic-qc --r-path /home/yli11/.conda/envs/hichipper/bin/R  --keep-temp-files --out hichipper_results hichipper.yaml
hichipper --r-path /home/yli11/.conda/envs/hichipper/bin/R  --keep-temp-files --out hichipper_results hichipper.yaml

=cut email 4 all

module load python/2.7.13

cd {{jid}}

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}








