#!shell


=cut bwa 1

inputFile=input

ncore=6
mem=30000
q={{queue}}

module load fastqc/0.11.5
module load conda3/202402
source activate /home/yli11/.conda/envs/captureC

add_umitag.py -r1 ${COL1} -r2  ${COL2} -o1 {{jid}}/${COL3}.r1.umitagged.fastq -o2 {{jid}}/${COL3}.r2.umitagged.fastq

fastqc ${COL1} -o {{jid}}

fastqc ${COL2} -o {{jid}}

cd {{jid}}

consolidate.py ${COL3}.r1.umitagged.fastq ${COL3}.r1.consolidated.fastq 10 0.49

consolidate.py ${COL3}.r2.umitagged.fastq ${COL3}.r2.consolidated.fastq 10 0.49

fastqc ${COL3}.r1.consolidated.fastq

fastqc ${COL3}.r2.consolidated.fastq

module load flash

flash ${COL3}.r1.consolidated.fastq ${COL3}.r2.consolidated.fastq --max-overlap=150 --min-overlap=10 --output-prefix=${COL3}

module load bwa/0.7.16a
module load samtools/1.7

bwa mem -t 6 {{index_file}} ${COL3}.extendedFrags.fastq > ${COL3}.sam
samtools sort -o ${COL3}.bam ${COL3}.sam
samtools index ${COL3}.bam
samtools flagstat ${COL3}.bam > ${COL3}.flagstat
samtools stats ${COL3}.bam > ${COL3}.stats

module load python/2.7.15-rhel7

bamCoverage -b ${COL3}.bam -o ${COL3}.CPM.bw -p 6 -bs 50 --normalizeUsing CPM 

=cut email 3 all

q={{queue}}

cd {{jid}}

module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
cp /home/yli11/HemTools/share/NGS_pipeline/multiqc_config.yaml .

multiqc .

export PATH=$PATH:"/home/yli11/HemTools/bin"

module load python/2.7.13


send_email_v1.py -a multiqc_report.html -m "{{jid}} is finished" -j {{jid}} --common


