#!shell

=cut iso 1 

ncore=10
mem=25000
q=priority

inputFile=input

module load smrttools/10.1

bam=$COL1
label=$COL2
primer={{primer}}
jid={{jid}}
genomeFasta=/home/yli11/Data/Human/hg38/fasta/hg38.fa
TCsrc=/home/yli11/Programs/TranscriptClean
# all hg38 format
SJ=/home/yli11/Programs/TranscriptClean/gencode_v40_SJs.tsv
SNP=/home/yli11/Data/Human/hg38/SNP150_iso_seq/00-common_all.vcf.gz
DB=/home/yli11/Data/Human/hg38/annotations/gencode_v40/talon.db



lima $bam \
$primer \
$jid/$label.bam \
--isoseq \
--num-threads 16 \
--min-score 0 \
--min-end-score 0 \
--min-signal-increase 10 \
--min-score-lead 0



isoseq3 refine $jid/$label.primer_5p--primer_3p.bam \
$primer \
$jid/$label.flnc.bam \
--min-polya-length 20 \
--require-polya \
--num-threads 16

# module load smrttools/10.1
isoseq3 cluster $jid/$label.flnc.bam $jid/$label.isoseq.cluster.bam --verbose --use-qvs



module load bedtools/2.30.0

bam2fastq -o $jid/$label.flnc -u $jid/$label.flnc.bam

module load conda3/202011

source activate /home/yli11/.conda/envs/captureC


/home/yli11/.conda/envs/captureC/bin/minimap2 -t 16 -ax splice:hq -uf --MD \
$genomeFasta \
$jid/$label.flnc.fastq \
> $jid/$label.Aligned.out.sam


/home/yli11/.conda/envs/captureC/bin/minimap2 -t 16 -ax splice:hq -uf --MD \
$genomeFasta \
$jid/$label.isoseq.cluster.hq.fasta.gz \
> $jid/$label.isoseq.cluster.sam

samtools view -bS $jid/$label.isoseq.cluster.sam > $jid/$label.isoseq.cluster.bam
samtools sort -@ 6 -o $jid/$label.isoseq.cluster.st.bam $jid/$label.isoseq.cluster.bam
samtools index $jid/$label.isoseq.cluster.st.bam

# done before running pipeline to generate these reference sets
# python ${TranscriptCleanPath}/accessory_scripts/get_SJs_from_gtf.py \
# --f ../gencode.v29.annotation.gtf \
# --g GRCh38.fa \
# --o gencode_v29_SJs.tsv

# zcat 00-common_all.vcf.gz | \
# awk '{if($0 !~ /^#/ && $0 !~ /^chr/) print "chr"$0; else print $0}' \
# > tmp_00-common_all.vcf
# gzip tmp_00-common_all.vcf
# mv tmp_00-common_all.vcf.gz 00-common_all.vcf.gz

# talon_initialize_database \
# --f gencode.v29.annotation.gtf \
# --a gencode_v29 \
# --g mm10 \
# --l 0 \
# --idprefix ENCODEH \
# --5p 500 \
# --3p 300 \
# --o talon.db

cd $jid

mkdir $label.results

mv -f $label.* $label.results/

cd $label.results

python $TCsrc/TranscriptClean.py \
--sam $label.Aligned.out.sam \
--genome $genomeFasta \
--spliceJns $SJ \
--correctMismatches true \
--correctIndels true \
--variants $SNP \
--maxLenIndel 5 \
--maxSJOffset 5 \
--threads 16 \
--canonOnly \
--outprefix $label.libraryID


# -rwxrwx--- 1 yli11 chenggrp 1.3M Jun  7 14:25 test.libraryID_clean.sam
# -rwxrwx--- 1 yli11 chenggrp 1.2M Jun  7 14:25 test.libraryID_clean.fa
# -rwxrwx--- 1 yli11 chenggrp  26K Jun  7 14:25 test.libraryID_clean.log
# -rwxrwx--- 1 yli11 chenggrp 163K Jun  7 14:25 test.libraryID_clean.TE.log

talon_label_reads --f $label.libraryID_clean.sam \
--g $genomeFasta \
--t 16 \
--ar 20 \
--o $label

# out: test_labeled.sam, test_read_labels.tsv
echo "$label,cellLine,PacBio,${label}_labeled.sam" > $label.config.csv

# cp $DB $label.db

# talon --f $label.config.csv \
# --db $label.db \
# --build hg38 \
# --cov 0.9 \
# --identity 0.8 \
# --o $label.final
# -t 20


# talon_abundance \
# --db $label.db \
# -a gencode_v40 \
# --build hg38 \
# --o $label.final

# talon_filter_transcripts \
# --db $label.db \
# -a gencode_v40 \
# --maxFracA 0.5 \
# --minCount 5 \
# --minDatasets 2 \
# --o $label.whitelist.csv

# talon_create_GTF \
# --db $label.db \
# -a gencode_v40 \
# -b hg38 \
# --whitelist $label.whitelist.csv \
# --o $label

# rm $label.db


=cut merge 2 iso

ncore=20
mem=20000
q=priority

module load conda3/202011

source activate /home/yli11/.conda/envs/captureC

jid={{jid}}
DB=/home/yli11/Data/Human/hg38/annotations/gencode_v40/talon.db

cd $jid

cat */*config.csv > config.csv

ln -s */*_labeled.sam .


cp $DB talon.db

talon --f config.csv \
--db talon.db \
--build hg38 \
--cov 0.9 \
--identity 0.8 \
--o merged.final \
-t 20


talon_abundance \
--db talon.db \
-a gencode_v40 \
--build hg38 \
--o merged.final

talon_filter_transcripts \
--db talon.db \
-a gencode_v40 \
--maxFracA 0.5 \
--minCount 5 \
--minDatasets 1 \
--o merged.whitelist.csv

talon_create_GTF \
--db talon.db \
-a gencode_v40 \
-b hg38 \
--whitelist merged.whitelist.csv \
--o merged

mkdir talon_abundance

mv merged* talon_abundance

cd talon_abundance

module load ucsc
gtfToGenePred merged_talon.gtf merged_talon.genePred
genePredToBed merged_talon.genePred merged_talon.bed12
module load bedtools
bedtools getfasta -fi /home/yli11/Data/Human/hg38/fasta/hg38.fa -bed merged_talon.bed12 -s -split -name -fo merged_talon.fa
module load kallisto
kallisto index --index=merged_talon merged_talon.fa
cpat.py -x /home/yli11/Data/Human/cpat/dat/Human_Hexamer.tsv --antisense -d /home/yli11/Data/Human/cpat/dat/Human_logitModel.RData --top-orf=5 -g merged_talon.fa -o cpat.predict

=cut annot 3 all

inputFile=input

ncore=1
mem=100000


module load conda3/202011

source activate /home/yli11/.conda/envs/captureC

cd {{jid}}

talon_sam_annot.py ${COL2}_labeled.sam ${COL2}.annot.sam talon_abundance/merged.final_talon_read_annot.tsv

module load samtools/1.9

samtools view -bS ${COL2}.annot.sam > ${COL2}.annot.bam
samtools sort -@ 6 -o ${COL2}.annot.st.bam ${COL2}.annot.bam
samtools index ${COL2}.annot.st.bam
rm ${COL2}.annot.bam
rm ${COL2}.annot.sam

=cut email 4 all

cd {{jid}}

module load python/2.7.13

send_email_v1.py  -m "{{jid}} is finished" -j {{jid}} 




