#!shell

=cut PB 1

ncore=30
mem=12000

module load conda3/202402

source activate /home/yli11/.conda/envs/isoquant/

output="{{jid}}_stringent_median_loose"
#gtf=/home/yli11/Data/Human/hg38/annotations/GCF_000001405.40.refseqNCBI.gtf
gtf=/home/yli11/Data/Human/hg38/annotations/gencode_v47/gencode.v47.canonical.gtf
# gtf=/home/yli11/Data/Human/hg38/annotations/gencode_v47/gencode.v47.canonical.add_BCL11A_all.gtf

genomeFasta=/home/yli11/Data/Human/hg38/fasta/hg38.fa
isoquant.py -d nanopore \
  --fastq *fastq* \
  --data_type nanopore \
  --clean_start \
  --reference $genomeFasta \
  --genedb $gtf \
  --complete_genedb \
  --high_memory  \
  --no_model_construction \
  --no_gtf_check  \
  --no_gzip  \
  --splice_correction_strategy default_ont  \
  --model_construction_strategy default_ont  \
  --polya_requirement always \
  --transcript_quantification unique_only \
  --gene_quantification unique_only \
  --matching_strategy precise \
  --output $output \
  --threads  $ncore
		
cd $output

cd OUT





cd aux

output="isoQuant_tequila_all"
isoquant.py -d nanopore \
  --bam *bam \
  --reference $genomeFasta \
  --genedb $gtf \
  --complete_genedb \
  --high_memory  \
  --no_gzip  \
  --splice_correction_strategy default_ont   \
  --model_construction_strategy all    \
  --polya_requirement auto \
  --matching_strategy default  \
  --output $output \
  --threads  $ncore


output="isoQuant_median_strigent"
isoquant.py -d nanopore \
  --bam *bam \
  --reference $genomeFasta \
  --genedb $gtf \
  --complete_genedb \
  --high_memory  \
  --no_gzip  \
  --splice_correction_strategy default_ont   \
  --model_construction_strategy default_ont     \
  --polya_requirement auto \
  --matching_strategy default  \
  --output $output \
  --threads  $ncore


output="isoQuant_loose"
isoquant.py -d nanopore \
  --bam *bam \
  --data_type nanopore \
  --reference $genomeFasta \
  --genedb $gtf \
  --complete_genedb \
  --high_memory  \
  --no_gzip  \
  --splice_correction_strategy all  \
  --model_construction_strategy all    \
  --polya_requirement auto \
  --transcript_quantification all  \
  --gene_quantification all  \
  --matching_strategy loose  \
  --output $output \
  --threads  $ncore

source activate /home/yli11/.conda/envs/captureC/


cd isoQuant_median_strigent/OUT

module load ucsc/051223 bedtools

gtfToGenePred OUT.extended_annotation.gtf OUT.extended_annotation.genePred
genePredToBed OUT.extended_annotation.genePred OUT.extended_annotation.bed12
bedtools getfasta -fi /home/yli11/Data/Human/hg38/fasta/hg38.fa -bed OUT.extended_annotation.bed12 -s -split -name -fo OUT.extended_annotation.fa
cpat.py -x /home/yli11/Data/Human/cpat/dat/Human_Hexamer.tsv --antisense -d /home/yli11/Data/Human/cpat/dat/Human_logitModel.RData --top-orf=5 -g OUT.extended_annotation.fa
 -o cpat.predict
	
	
cd ../..
cd isoQuant_loose/OUT


gtfToGenePred OUT.extended_annotation.gtf OUT.extended_annotation.genePred
genePredToBed OUT.extended_annotation.genePred OUT.extended_annotation.bed12
bedtools getfasta -fi /home/yli11/Data/Human/hg38/fasta/hg38.fa -bed OUT.extended_annotation.bed12 -s -split -name -fo OUT.extended_annotation.fa
cpat.py -x /home/yli11/Data/Human/cpat/dat/Human_Hexamer.tsv --antisense -d /home/yli11/Data/Human/cpat/dat/Human_logitModel.RData --top-orf=5 -g OUT.extended_annotation.fa
 -o cpat.predict



cd ../..
cd isoQuant_tequila_all/OUT


gtfToGenePred OUT.extended_annotation.gtf OUT.extended_annotation.genePred
genePredToBed OUT.extended_annotation.genePred OUT.extended_annotation.bed12
bedtools getfasta -fi /home/yli11/Data/Human/hg38/fasta/hg38.fa -bed OUT.extended_annotation.bed12 -s -split -name -fo OUT.extended_annotation.fa
cpat.py -x /home/yli11/Data/Human/cpat/dat/Human_Hexamer.tsv --antisense -d /home/yli11/Data/Human/cpat/dat/Human_logitModel.RData --top-orf=5 -g OUT.extended_annotation.fa
 -o cpat.predict

