#!shell

# processing ISO-seq using expresso

=cut iso 1 

ncore=16
mem=12000


# input sorted algined bam or sam file
gtf=/home/yli11/Data/Human/hg38/annotations/GCF_000001405.40.refseqNCBI.gtf
genomeFasta=/home/yli11/Data/Human/hg38/fasta/hg38.fa

module load bedtools/2.30.0 samtools/1.15.1
module load hmmer/3.3.2 perl/5.28.1  blast/2.9.0  samtools/1.9 ucsc

cd {{jid}}

cp ../samples.tsv .


src=/home/yli11/Programs/espresso_v_1_4_0/src


perl $src/ESPRESSO_S.pl -A $gtf -L samples.tsv -F $genomeFasta -O work_dir -T $ncore

awk '{print NR-1}' samples.tsv | while read line_number; do
  echo $line_number
  perl $src/ESPRESSO_C.pl -I work_dir -F $genomeFasta -X $line_number -T $ncore
done

perl $src/ESPRESSO_Q.pl -T $ncore -A $gtf -L work_dir/samples.tsv.updated -V work_dir/samples.compatible_isoform.tsv

# /home/yli11/.conda/envs/captureC/bin/python /home/yli11/HemTools/bin/Espresso_subset_bam.py $COL2



=cut email 3 all

cd {{jid}}

module load python/2.7.13

send_email_v1.py  -m "{{jid}} is finished" -j {{jid}} 




