#!shell

# processing ISO-seq using expresso

=cut iso 1 

ncore=5
mem=30000

inputFile=input
# input sorted algined bam or sam file


# pacbio bam file, this is basically a fastq file
# sam=$COL1, give abs path
# label=$COL2
# give abs path
genomeFasta=/home/yli11/Data/Human/hg38/fasta/hg38.fa
# genomeFasta=/home/yli11/Programs/espresso/test_data/test_data_espresso_sirv/SIRV2.fasta
# gtf=/home/yli11/Programs/espresso/test_data/test_data_espresso_sirv/SIRV_C.gtf
gtf=/home/yli11/Data/Human/hg38/annotations/gencode_v40/gencode.v40.annotation.gtf
module load conda3/202011

source activate captureC

module load hmmer/3.3.2 perl/5.28.1  blast/2.9.0  samtools/1.9 ucsc

cd {{jid}}

echo $COL1$'\t'$COL2 > ${COL2}.sample.tsv

src=/home/yli11/Programs/espresso/src

perl $src/ESPRESSO_S.pl -A $gtf -L ${COL2}.sample.tsv -F $genomeFasta -O ${COL2}_result -T 5

perl $src/ESPRESSO_C.pl -I ${COL2}_result -F $genomeFasta -X 0 -T 5

perl $src/ESPRESSO_Q.pl -T 5 -A $gtf -L ${COL2}_result/${COL2}.sample.tsv.updated -V ${COL2}_result/${COL2}_isoform.tsv

# python $src/visualize.py --genome-fasta $genomeFasta --updated-gtf ${COL2}_result/sample_N2_R0_updated.gtf --abundance-esp ${COL2}_result/sample_N2_R0_abundance.esp --target-gene SIRV2 --minimum-count 1 --descriptive-name SIRV --output-dir ${COL2}_result/visualization
python $src/visualize.py --genome-fasta $genomeFasta --updated-gtf ${COL2}_result/sample_N2_R0_updated.gtf --abundance-esp ${COL2}_result/sample_N2_R0_abundance.esp --target-gene BCL11A --minimum-count 1 --descriptive-name BCL11A --output-dir ${COL2}_result/visualization



=cut email 3 all

cd {{jid}}

module load python/2.7.13

send_email_v1.py  -m "{{jid}} is finished" -j {{jid}} 




