#!shell

=cut NM 1

inputFile=input

ncore=1
mem=50000


module load star/2.5.3a
module load ucsc

chrom_sizes={{chrom_size}}


# STAR --runMode inputAlignmentsFromBAM --inputBAMfile ${COL1} --outWigType bedGraph --outWigStrand Stranded --outFileNamePrefix ./test/ 

region="chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr17 chr18 chr19 chr20 chr22 chrX"

module load samtools/1.7

samtools view -b ${COL1} $region > {{jid}}/${COL2}.tmp.bam

cd {{jid}}

samtools sort -o ${COL2}.tmp.st.bam ${COL2}.tmp.bam

samtools index ${COL2}.tmp.st.bam

STAR --runMode inputAlignmentsFromBAM --inputBAMfile ${COL2}.tmp.st.bam --outWigType bedGraph --outWigStrand Stranded --outFileNamePrefix ${COL2} 

bedGraphToBigWig ${COL2}Signal.UniqueMultiple.str1.out.bg $chrom_sizes ${COL2}_minusAll.bw
bedGraphToBigWig ${COL2}Signal.Unique.str1.out.bg         $chrom_sizes ${COL2}_minusUniq.bw
bedGraphToBigWig ${COL2}Signal.UniqueMultiple.str2.out.bg $chrom_sizes ${COL2}_plusAll.bw
bedGraphToBigWig ${COL2}Signal.Unique.str2.out.bg         $chrom_sizes ${COL2}_plusUniq.bw

STAR --runMode inputAlignmentsFromBAM --inputBAMfile ${COL2}.tmp.st.bam --outWigType bedGraph --outWigStrand Unstranded --outFileNamePrefix ${COL2}  


bedGraphToBigWig ${COL2}Signal.UniqueMultiple.str1.out.bg $chrom_sizes ${COL2}_all.bw
bedGraphToBigWig ${COL2}Signal.Unique.str1.out.bg         $chrom_sizes ${COL2}_uniq.bw

rm ${COL2}.tmp.bam

rm ${COL2}.tmp.st.bam*

# f=${COL2}Signal.UniqueMultiple.str1.out.bg
# grep -v chrM $f > $f.rmchrM
# bedGraphToBigWig	$f.rmchrM	$chrom_sizes	${COL2}_minusAll.bw
# f=${COL2}Signal.Unique.str1.out.bg
# grep -v chrM $f > $f.rmchrM
# bedGraphToBigWig	$f.rmchrM	$chrom_sizes	${COL2}_minusUniq.bw
# f=${COL2}Signal.UniqueMultiple.str2.out.bg
# grep -v chrM $f > $f.rmchrM
# bedGraphToBigWig	$f.rmchrM	$chrom_sizes	${COL2}_plusAll.bw
# f=${COL2}Signal.Unique.str2.out.bg
# grep -v chrM $f > $f.rmchrM
# bedGraphToBigWig	$f.rmchrM	$chrom_sizes	${COL2}_plusUniq.bw
# f=${COL2}Signal.UniqueMultiple.str1.out.bg
# grep -v chrM $f > $f.rmchrM
# bedGraphToBigWig	$f.rmchrM	$chrom_sizes	${COL2}_all.bw
# f=${COL2}Signal.Unique.str1.out.bg
# grep -v chrM $f > $f.rmchrM
# bedGraphToBigWig	$f.rmchrM	$chrom_sizes	${COL2}_uniq.bw

=cut email 4 all

module load python/2.7.13


cd {{jid}}

mv *out.bg log_files

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}





