#!shell




=cut bamtobdg 1 

# module load conda3

# source activate /home/yli11/.conda/envs/cut_run

inputFile=converter_input

ncore=1
mem=20000


module load bedops/2.4.35
module load ucsc/051223

# bigwigCompare -b1 ${COL1} -b2 ${COL1} --operation first -o ${COL2} -of bedgraph --numberOfProcessors 10 -bs {{binSize}} --blackListFileName {{black_list}}

bedops --chop {{binSize}} --stagger {{binSize}} {{chrom_size_bed}} | awk -F "\t" '{print $1"\t"$2"\t"$3"\t"$1":"$2"-"$3}' > ${COL2}.bed

bigWigAverageOverBed ${COL1} ${COL2}.bed ${COL2}.tmp -bedOut=${COL2}.out

cut -f 1,2,3,5 ${COL2}.out > ${COL2}

rm ${COL2}.tmp
rm ${COL2}.out
rm ${COL2}.bed



=cut S3norm 2 bamtobdg

module load conda3

source activate /home/yli11/.conda/envs/S3norm

module load R/4.2.0

alias python='/home/yli11/.conda/envs/S3norm/bin/python'
unset PYTHONPATH

ncore=1
mem=200000
q=priority

S3norm_src=/home/yli11/HemTools/share/script/S3norm

# time python $S3norm_src/s3norm_pipeline.py -s $S3norm_src/ -t {{S3norm_input}} -r mean -l 0.1 -i 10 -f 0.01 -b 1 
time python $S3norm_src/s3norm_pipeline.py -s $S3norm_src/ -t {{S3norm_input}} -r mean -f 0.01

for i in `cat {{S3norm_input}}`;do mv $i* {{jid}}/log_files/;done

=cut bdg_to_bw 3 S3norm

inputFile=bdg_to_bw_files

ncore=1
mem=30000
q=priority

module load ucsc/051223/051223 bedtools

cd S3norm_NBP_bedgraph

bedtools intersect -a ${COL1} -b {{chrom_size_bed}} -u > ${COL1}.tmp
mv ${COL1}.tmp ${COL1}

bedGraphToBigWig ${COL1} {{chrom_size}} ${COL2}

cd ..

cd S3norm_rc_bedgraph

bedtools intersect -a ${COL1} -b {{chrom_size_bed}} -u > ${COL1}.tmp
mv ${COL1}.tmp ${COL1}

bedGraphToBigWig ${COL1} {{chrom_size}} ${COL2}


=cut email 4 all

module load python/2.7.13

mv -f S3norm_NBP_bedgraph {{jid}}
mv -f S3norm_rc_bedgraph {{jid}}
mv -f NBP_bedgraph {{jid}}
mv -f average_ref_bedgraph {{jid}}
mv {{jid}}*input {{jid}}/log_files
cd {{jid}}

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}



# bedops --chop 50 --stagger 50 /home/yli11/Data/Human/hg19/annotations/hg19_main.chrom_sizes.bed | bedmap --faster --echo --max --delim "\t" - 1631313_RFA008.all.bw.bdg > answer.bed


