#!shell




=cut bamtobdg 1 

module load conda3

source activate /home/yli11/.conda/envs/cut_run

inputFile=converter_input

ncore=1
mem=40000
q=priority

bamCoverage -b ${COL1} -o ${COL2} -of bedgraph --ignoreForNormalization chrX chrM   --numberOfProcessors 10 -bs {{binSize}} --smoothLength {{smoothLength}} --blackListFileName {{black_list}}
# GM12878output1.s3norm.bdg.s3norm.bedgraph
module load bedtools

if [ -z "{{peak_dir}}"]; then
	echo "whole genome normalization"
else
	cat {{peak_dir}}/*{{file_name_pattern}}* > ${COL2}.tmp.peak.bed
	module load bedops;bedops --range 5000 -u ${COL2}.tmp.peak.bed > ${COL2}.tmp.peak.bed2
	bedtools intersect -a ${COL2} -b ${COL2}.tmp.peak.bed2 -u > ${COL2}.tmp
	mv ${COL2} ${COL2}.all
	mv ${COL2}.tmp ${COL2}
	rm ${COL2}.tmp.peak.bed
	rm ${COL2}.tmp.peak.bed2
fi



=cut S3norm 2 bamtobdg

module load conda3

source activate /home/yli11/.conda/envs/S3norm

module load R/3.5.1

ncore=1
mem=100000
q=priority

S3norm_src=/home/yli11/HemTools/share/script/S3norm

# time python $S3norm_src/s3norm_pipeline.py -s $S3norm_src/ -t {{S3norm_input}} -r mean -l 0.1 -i 10 -f 0.01 -b 1 
time python $S3norm_src/s3norm_pipeline.py -s $S3norm_src/ -t {{S3norm_input}} -r mean -f 0.01

for i in `cat {{S3norm_input}}`;do mv $i* {{jid}}/log_files/;done

=cut bdg_to_bw 3 S3norm

inputFile=bdg_to_bw_files

ncore=1
mem=30000
q=priority

module load ucsc/041619

cd S3norm_NBP_bedgraph

bedGraphToBigWig ${COL1} {{chrom_size}} ${COL2}

cd ..

cd S3norm_rc_bedgraph

bedGraphToBigWig ${COL1} {{chrom_size}} ${COL2}


=cut email 4 all

module load python/2.7.13

mv -f S3norm_NBP_bedgraph {{jid}}
mv -f S3norm_rc_bedgraph {{jid}}
mv -f NBP_bedgraph {{jid}}
mv -f average_ref_bedgraph {{jid}}
mv {{jid}}*input {{jid}}/log_files
cd {{jid}}

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}



# bedops --chop 50 --stagger 50 /home/yli11/Data/Human/hg19/annotations/hg19_main.chrom_sizes.bed | bedmap --faster --echo --max --delim "\t" - 1631313_RFA008.all.bw.bdg > answer.bed


