#!shell
=cut trinity 1

inputFile=input

ncore=20
mem=6000
# ncore=1
# mem=50000
q=priority

module load trinity/2.5.0

Trinity --seqType fq --left ${COL1} --right ${COL2} --CPU 20 --max_memory 100G --output ${COL3}_trinity_out

cd  ${COL3}_trinity_out

module load kallisto/0.43.1

kallisto index -i ${COL3}_KI Trinity.fasta

cd ..

kallisto quant -i ${COL3}_trinity_out/${COL3}_KI --threads=20 --bootstrap-samples=100 --output-dir=${COL3}_trinity_out/${COL3}_abundance ${COL1} ${COL2}

module load conda3/202011

source activate /home/yli11/.conda/envs/captureC

cd  ${COL3}_trinity_out

genomeFasta=/home/yli11/Data/Human/hg38/fasta/hg38.main.fa

/home/yli11/.conda/envs/captureC/bin/minimap2 -t 20 -ax splice:hq -uf --MD $genomeFasta Trinity.fasta > Trinity.sam

samtools view -bS Trinity.sam > ${COL3}.bam
samtools sort -@ 20 -o ${COL3}.st.bam ${COL3}.bam
samtools index ${COL3}.st.bam

rm ${COL3}.bam
rm Trinity.sam
samtools view ${COL3}.st.bam chr2:60398545-60606441 | awk '{print $1}' > ${COL3}.BCL11A.readlist

# cd ${COL3}_abundance

# [yli11@nodecn202 6_KO_abundance]$ table_subset.py abundance.tsv 1
# (168090, 5)
# [yli11@nodecn202 6_KO_abundance]$ wc -l *.list
# 168090 read.cutoff.1.0.list

# module load python/2.7.13

# table_subset.py abundance.tsv 1

# table_subset.py abundance.tsv 2

# table_subset.py abundance.tsv 5

# module load java/1.8.0_181

# cd ..

# readList=${COL3}_abundance/read.cutoff.1.0.list
# outBam=trinity_gmap.NFIX.tpm1.bam

# java -jar /hpcf/apps/picard/install/2.9.4/picard.jar FilterSamReads I=trinity_gmap.NFIX.bam O=$outBam READ_LIST_FILE=$readList FILTER=includeReadList;samtools index $outBam

# readList=${COL3}_abundance/read.cutoff.2.0.list
# outBam=trinity_gmap.NFIX.tpm2.bam

# java -jar /hpcf/apps/picard/install/2.9.4/picard.jar FilterSamReads I=trinity_gmap.NFIX.bam O=$outBam READ_LIST_FILE=$readList FILTER=includeReadList;samtools index $outBam


# readList=${COL3}_abundance/read.cutoff.5.0.list
# outBam=trinity_gmap.NFIX.tpm5.bam

# java -jar /hpcf/apps/picard/install/2.9.4/picard.jar FilterSamReads I=trinity_gmap.NFIX.bam O=$outBam READ_LIST_FILE=$readList FILTER=includeReadList;samtools index $outBam


=cut email 4 all

module load python/2.7.13

cd {{jid}}

send_email_v1.py -m "{{jid}} is finished" -j {{jid}}


