#!shell
=cut Uditas 1

inputFile=input

ncore=2
mem=20000

module load conda3

source activate /home/yli11/.conda/envs/uditas_env

export BOWTIE2_INDEXES=/home/yli11/Data/Human/hg38/bowtie2/

export GENOMES_2BIT=/home/yli11/Data/Human/hg38/

module load bowtie2/2.2.9

module load java/1.8.0_181

uditasHBG $PWD -process_amplicon ${COL1}

=cut summary 2 Uditas

module load conda3

source activate /home/yli11/.conda/envs/uditas_env

export BOWTIE2_INDEXES=/home/yli11/Data/Human/hg38/bowtie2/

export GENOMES_2BIT=/home/yli11/Data/Human/hg38/

module load bowtie2/2.2.9

module load java/1.8.0_181

uditasHBG $PWD -only_summarize 1

module load python/2.7.13

send_email_v1.py -m "UditasHBG pipeline is finished!" -j UditasHBG


